from django.contrib import admin
from django.urls import path
from sistema import views

urlpatterns = [
    path('', views.index, name="index"),
    path('modulos/', views.modulos, name="modulos"),
    path('login', views.loginf, name="login"),
    path('logout', views.logoutUser, name="logout"),
    path('403', views.loginf403, name="403"),
    path('4dmdj', admin.site.urls),
    path('admin', views.usuarios, name="admin"),
    path('admin/update/<int:id>', views.update_usuarios, name="update_usuarios"),
    path('admin/updatep/<int:id>', views.updatep_usuarios, name="updatep_usuarios"),
    path('admin/delete/<int:id>', views.del_usuarios, name="del_usuarios"),
    path('admin/departamentos', views.departamentos, name="departamentos"),
    path('admin/departamentos/update/<int:id>', views.update_departamentos, name="update_departamentos"),
    path('admin/departamentos/delete/<int:id>', views.del_departamentos, name="del_departamentos"),
    path('admin/sedes', views.sedes, name="sedes"),
    path('admin/sedes/update/<int:id>', views.update_sedes, name="update_sedes"),
    path('admin/sedes/delete/<int:id>', views.del_sedes, name="del_sedes"),
    path('organizacion', views.organizacion, name="organizacion"),
    path('organizacion/reglamentos', views.reglamentos, name="reglamentos"),
    path('organizacion/reglamentos/update/<int:id>', views.update_reglamentos, name="update_reglamentos"),
    path('organizacion/reglamentos/updatef/<int:id>', views.update_reglamentosf, name="update_reglamentosf"),
    path('organizacion/reglamentos/delete/<int:id>', views.del_reglamentos, name="del_reglamentos"),
    path('organizacion/normativas', views.normativas, name="normativas"),
    path('organizacion/normativas/update/<int:id>', views.update_normativas, name="update_normativas"),
    path('organizacion/normativas/updatef/<int:id>', views.update_normativasf, name="update_normativasf"),
    path('organizacion/normativas/delete/<int:id>', views.del_normativas, name="del_normativas"),
    path('seguridad/', views.seguridad, name="seguridad"),
    path('seguridad/entradap', views.entradap, name="entradap"),
    path('seguridad/entradap/update/<int:id>', views.update_entradap, name="update_entradap"),
    path('seguridad/entradap/delete/<int:id>', views.del_entradap, name="del_entradap"),
    path('seguridad/salidap', views.salidap, name="salidap"),
    path('seguridad/salidap/update/<int:id>', views.update_salidap, name="update_salidap"),
    path('seguridad/salidap/delete/<int:id>', views.del_salidap, name="del_salidap"),
    path('seguridad/gestion', views.gestions, name="gestions"),
    path('seguridad/gestion/update/<int:id>', views.update_gestion, name="update_gestion"),
    path('seguridad/gestion/delete/<int:id>', views.del_gestion, name="del_gestion"),
    path('seguridad/vehiculos', views.vehiculos, name="vehiculos"),
    path('seguridad/vehiculos/update/<int:id>', views.update_vehiculos, name="update_vehiculos"),
    path('seguridad/vehiculos/delete/<int:id>', views.del_vehiculos, name="del_vehiculos"),
    path('presupuesto/', views.presupuesto, name="presupuesto"),
    path('presupuesto/update/<int:id>', views.update_presupuesto, name="update_presupuesto"),
    path('presupuesto/delete/<int:id>', views.del_presupuesto, name="del_presupuesto"),
    path('presupuesto/asignacion', views.asignacion, name="asignacion"),
    path('presupuesto/traspasos', views.traspasos, name="traspasos"),
    path('planificacion/', views.planificacion, name="planificacion"),
    path('gestion', views.gestionh, name="gestionh"),
    path('potencia', views.potencia, name="potencia"),
    path('potencia/update/<int:id>', views.update_potencia, name="update_potencia"),
    path('potencia/delete/<int:id>', views.del_potencia, name="update_potencia"),
    ]

AUTH_USER_MODEL = 'sistema.UserC'

