# Generated by Django 4.1.8 on 2023-11-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_remove_userc_ci_alter_userc_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userc',
            name='apellido',
            field=models.CharField(default='', max_length=200, verbose_name='Apellido:'),
        ),
        migrations.AlterField(
            model_name='userc',
            name='departamento',
            field=models.CharField(default='', max_length=200, verbose_name='Departamento:'),
        ),
        migrations.AlterField(
            model_name='userc',
            name='nombre',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre:'),
        ),
        migrations.AlterField(
            model_name='userc',
            name='password',
            field=models.CharField(default='', max_length=200, verbose_name='Contraseña:'),
        ),
        migrations.AlterField(
            model_name='userc',
            name='sede',
            field=models.CharField(default='', max_length=200, verbose_name='Sede:'),
        ),
        migrations.AlterField(
            model_name='userc',
            name='tipo',
            field=models.CharField(choices=[('estandar', 'estandar'), ('admin', 'admin'), ('superu', 'superu')], default='', max_length=200, verbose_name='Tipo de Usuario:'),
        ),
        migrations.AlterField(
            model_name='userc',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Cédula:'),
        ),
    ]
