# Generated by Django 4.2.7 on 2023-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_sedes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=64, verbose_name='Nombre:')),
                ('apellido', models.CharField(default='', max_length=64, verbose_name='Apellido:')),
                ('cedula', models.CharField(default='', max_length=64, verbose_name='Cédula:')),
                ('transporte', models.CharField(default='', max_length=64, verbose_name='Transporte:')),
                ('modelo', models.CharField(default='', max_length=64, verbose_name='Modelo:')),
                ('placa', models.CharField(default='', max_length=64, verbose_name='Placa:')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.CharField(default='', max_length=64, verbose_name='Hora:')),
            ],
        ),
    ]
