# Generated by Django 4.2.7 on 2023-12-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_personal_presupuesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='updated',
        ),
    ]
