# Generated by Django 4.2.7 on 2023-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_remove_personal_creador_remove_personal_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('sede', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('tipoincidencia', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('observaciones', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'incidencia',
                'verbose_name_plural': 'incidencias',
            },
        ),
    ]
