# Generated by Django 4.2.7 on 2023-12-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_incidencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='departamento',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='estado',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='observaciones',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='sede',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='tipoincidencia',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='usuario',
            field=models.CharField(max_length=300),
        ),
    ]
